name: Handle Issues
on : [issues]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue information
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue URL: ${{ github.event.issue.html_url }}"